export const COUNTRIES = [
  { id: 'Afghanistan', text: 'Afghanistan' },
  { id: 'Albania', text: 'Albania' },
  { id: 'Algeria', text: 'Algeria' },
  { id: 'Andorra', text: 'Andorra' },
  { id: 'Angola', text: 'Angola' },
  { id: 'Anguilla', text: 'Anguilla' },
  { id: 'Antigua &amp; Barbuda', text: 'Antigua &amp; Barbuda' },
  { id: 'Argentina', text: 'Argentina' },
  { id: 'Armenia', text: 'Armenia' },
  { id: 'Aruba', text: 'Aruba' },
  { id: 'Australia', text: 'Australia' },
  { id: 'Austria', text: 'Austria' },
  { id: 'Azerbaijan', text: 'Azerbaijan' },
  { id: 'Bahamas', text: 'Bahamas' },
  { id: 'Bahrain', text: 'Bahrain' },
  { id: 'Bangladesh', text: 'Bangladesh' },
  { id: 'Barbados', text: 'Barbados' },
  { id: 'Belarus', text: 'Belarus' },
  { id: 'Belgium', text: 'Belgium' },
  { id: 'Belize', text: 'Belize' },
  { id: 'Benin', text: 'Benin' },
  { id: 'Bermuda', text: 'Bermuda' },
  { id: 'Bhutan', text: 'Bhutan' },
  { id: 'Bolivia', text: 'Bolivia' },
  { id: 'Bosnia &amp; Herzegovina', text: 'Bosnia &amp; Herzegovina' },
  { id: 'Botswana', text: 'Botswana' },
  { id: 'Brazil', text: 'Brazil' },
  { id: 'British Virgin Islands', text: 'British Virgin Islands' },
  { id: 'Brunei', text: 'Brunei' },
  { id: 'Bulgaria', text: 'Bulgaria' },
  { id: 'Burkina Faso', text: 'Burkina Faso' },
  { id: 'Burundi', text: 'Burundi' },
  { id: 'Cambodia', text: 'Cambodia' },
  { id: 'Cameroon', text: 'Cameroon' },
  { id: 'Cape Verde', text: 'Cape Verde' },
  { id: 'Cayman Islands', text: 'Cayman Islands' },
  { id: 'Chad', text: 'Chad' },
  { id: 'Chile', text: 'Chile' },
  { id: 'China', text: 'China' },
  { id: 'Colombia', text: 'Colombia' },
  { id: 'Congo', text: 'Congo' },
  { id: 'Cook Islands', text: 'Cook Islands' },
  { id: 'Costa Rica', text: 'Costa Rica' },
  { id: 'Cote D Ivoire', text: 'Cote D Ivoire' },
  { id: 'Croatia', text: 'Croatia' },
  { id: 'Cruise Ship', text: 'Cruise Ship' },
  { id: 'Cuba', text: 'Cuba' },
  { id: 'Cyprus', text: 'Cyprus' },
  { id: 'Czech Republic', text: 'Czech Republic' },
  { id: 'Denmark', text: 'Denmark' },
  { id: 'Djibouti', text: 'Djibouti' },
  { id: 'Dominica', text: 'Dominica' },
  { id: 'Dominican Republic', text: 'Dominican Republic' },
  { id: 'Ecuador', text: 'Ecuador' },
  { id: 'Egypt', text: 'Egypt' },
  { id: 'El Salvador', text: 'El Salvador' },
  { id: 'Equatorial Guinea', text: 'Equatorial Guinea' },
  { id: 'Estonia', text: 'Estonia' },
  { id: 'Ethiopia', text: 'Ethiopia' },
  { id: 'Falkland Islands', text: 'Falkland Islands' },
  { id: 'Faroe Islands', text: 'Faroe Islands' },
  { id: 'Fiji', text: 'Fiji' },
  { id: 'Finland', text: 'Finland' },
  { id: 'France', text: 'France' },
  { id: 'French Polynesia', text: 'French Polynesia' },
  { id: 'French West Indies', text: 'French West Indies' },
  { id: 'Gabon', text: 'Gabon' },
  { id: 'Gambia', text: 'Gambia' },
  { id: 'Georgia', text: 'Georgia' },
  { id: 'Germany', text: 'Germany' },
  { id: 'Ghana', text: 'Ghana' },
  { id: 'Gibraltar', text: 'Gibraltar' },
  { id: 'Greece', text: 'Greece' },
  { id: 'Greenland', text: 'Greenland' },
  { id: 'Grenada', text: 'Grenada' },
  { id: 'Guam', text: 'Guam' },
  { id: 'Guatemala', text: 'Guatemala' },
  { id: 'Guernsey', text: 'Guernsey' },
  { id: 'Guinea', text: 'Guinea' },
  { id: 'Guinea Bissau', text: 'Guinea Bissau' },
  { id: 'Guyana', text: 'Guyana' },
  { id: 'Haiti', text: 'Haiti' },
  { id: 'Honduras', text: 'Honduras' },
  { id: 'Hong Kong', text: 'Hong Kong' },
  { id: 'Hungary', text: 'Hungary' },
  { id: 'Iceland', text: 'Iceland' },
  { id: 'India', text: 'India' },
  { id: 'Indonesia', text: 'Indonesia' },
  { id: 'Iran', text: 'Iran' },
  { id: 'Iraq', text: 'Iraq' },
  { id: 'Ireland', text: 'Ireland' },
  { id: 'Isle of Man', text: 'Isle of Man' },
  { id: 'Israel', text: 'Israel' },
  { id: 'Italy', text: 'Italy' },
  { id: 'Jamaica', text: 'Jamaica' },
  { id: 'Japan', text: 'Japan' },
  { id: 'Jersey', text: 'Jersey' },
  { id: 'Jordan', text: 'Jordan' },
  { id: 'Kazakhstan', text: 'Kazakhstan' },
  { id: 'Kenya', text: 'Kenya' },
  { id: 'Kuwait', text: 'Kuwait' },
  { id: 'Kyrgyz Republic', text: 'Kyrgyz Republic' },
  { id: 'Laos', text: 'Laos' },
  { id: 'Latvia', text: 'Latvia' },
  { id: 'Lebanon', text: 'Lebanon' },
  { id: 'Lesotho', text: 'Lesotho' },
  { id: 'Liberia', text: 'Liberia' },
  { id: 'Libya', text: 'Libya' },
  { id: 'Liechtenstein', text: 'Liechtenstein' },
  { id: 'Lithuania', text: 'Lithuania' },
  { id: 'Luxembourg', text: 'Luxembourg' },
  { id: 'Macau', text: 'Macau' },
  { id: 'Macedonia', text: 'Macedonia' },
  { id: 'Madagascar', text: 'Madagascar' },
  { id: 'Malawi', text: 'Malawi' },
  { id: 'Malaysia', text: 'Malaysia' },
  { id: 'Maldives', text: 'Maldives' },
  { id: 'Mali', text: 'Mali' },
  { id: 'Malta', text: 'Malta' },
  { id: 'Mauritania', text: 'Mauritania' },
  { id: 'Mauritius', text: 'Mauritius' },
  { id: 'Mexico', text: 'Mexico' },
  { id: 'Moldova', text: 'Moldova' },
  { id: 'Monaco', text: 'Monaco' },
  { id: 'Mongolia', text: 'Mongolia' },
  { id: 'Montenegro', text: 'Montenegro' },
  { id: 'Montserrat', text: 'Montserrat' },
  { id: 'Morocco', text: 'Morocco' },
  { id: 'Mozambique', text: 'Mozambique' },
  { id: 'Namibia', text: 'Namibia' },
  { id: 'Nepal', text: 'Nepal' },
  { id: 'Netherlands', text: 'Netherlands' },
  { id: 'New Caledonia', text: 'New Caledonia' },
  { id: 'New Zealand', text: 'New Zealand' },
  { id: 'Nicaragua', text: 'Nicaragua' },
  { id: 'Niger', text: 'Niger' },
  { id: 'Nigeria', text: 'Nigeria' },
  { id: 'Norway', text: 'Norway' },
  { id: 'Oman', text: 'Oman' },
  { id: 'Pakistan', text: 'Pakistan' },
  { id: 'Palestine', text: 'Palestine' },
  { id: 'Panama', text: 'Panama' },
  { id: 'Paraguay', text: 'Paraguay' },
  { id: 'Peru', text: 'Peru' },
  { id: 'Philippines', text: 'Philippines' },
  { id: 'Poland', text: 'Poland' },
  { id: 'Portugal', text: 'Portugal' },
  { id: 'Puerto Rico', text: 'Puerto Rico' },
  { id: 'Qatar', text: 'Qatar' },
  { id: 'Romania', text: 'Romania' },
  { id: 'Russia', text: 'Russia' },
  { id: 'Senegal', text: 'Senegal' },
  { id: 'Seychelles', text: 'Seychelles' },
  { id: 'Singapore', text: 'Singapore' },
  { id: 'South Africa', text: 'South Africa' },
  { id: 'South Korea', text: 'South Korea' },
  { id: 'Spain', text: 'Spain' },
  { id: 'Sweden', text: 'Sweden' },
  { id: 'Switzerland', text: 'Switzerland' },
  { id: 'Syria', text: 'Syria' },
  { id: 'Taiwan', text: 'Taiwan' },
  { id: 'Tanzania', text: 'Tanzania' },
  { id: 'Thailand', text: 'Thailand' },
  { id: 'Trinidad &amp; Tobago', text: 'Trinidad &amp; Tobago' },
  { id: 'Tunisia', text: 'Tunisia' },
  { id: 'Turkey', text: 'Turkey' },
  { id: 'Uganda', text: 'Uganda' },
  { id: 'Ukraine', text: 'Ukraine' },
  { id: 'United Arab Emirates', text: 'United Arab Emirates' },
  { id: 'United Kingdom', text: 'United Kingdom' },
  { id: 'United States of America', text: 'United States of America' },
  { id: 'Uruguay', text: 'Uruguay' },
  { id: 'Uzbekistan', text: 'Uzbekistan' },
  { id: 'Venezuela', text: 'Venezuela' },
  { id: 'Vietnam', text: 'Vietnam' },
  { id: 'Virgin Islands (US)', text: 'Virgin Islands (US)' },
  { id: 'Zambia', text: 'Zambia' },
  { id: 'Zimbabwe', text: 'Zimbabwe' },
];
