export const COUNTRIES = [
  { id: 'afghanistan', text: 'afghanistan' },
  { id: 'albania', text: 'albania' },
  { id: 'algeria', text: 'algeria' },
  { id: 'andorra', text: 'andorra' },
  { id: 'angola', text: 'angola' },
  { id: 'anguilla', text: 'anguilla' },
  { id: 'antigua &amp; barbuda', text: 'antigua &amp; barbuda' },
  { id: 'argentina', text: 'argentina' },
  { id: 'armenia', text: 'armenia' },
  { id: 'aruba', text: 'aruba' },
  { id: 'australia', text: 'australia' },
  { id: 'austria', text: 'austria' },
  { id: 'azerbaijan', text: 'azerbaijan' },
  { id: 'bahamas', text: 'bahamas' },
  { id: 'bahrain', text: 'bahrain' },
  { id: 'bangladesh', text: 'bangladesh' },
  { id: 'barbados', text: 'barbados' },
  { id: 'belarus', text: 'belarus' },
  { id: 'belgium', text: 'belgium' },
  { id: 'belize', text: 'belize' },
  { id: 'benin', text: 'benin' },
  { id: 'bermuda', text: 'bermuda' },
  { id: 'bhutan', text: 'bhutan' },
  { id: 'bolivia', text: 'bolivia' },
  { id: 'bosnia &amp; herzegovina', text: 'bosnia &amp; herzegovina' },
  { id: 'botswana', text: 'botswana' },
  { id: 'brazil', text: 'brazil' },
  { id: 'british virgin islands', text: 'british virgin islands' },
  { id: 'brunei', text: 'brunei' },
  { id: 'bulgaria', text: 'bulgaria' },
  { id: 'burkina faso', text: 'burkina faso' },
  { id: 'burundi', text: 'burundi' },
  { id: 'cambodia', text: 'cambodia' },
  { id: 'cameroon', text: 'cameroon' },
  { id: 'cape verde', text: 'cape verde' },
  { id: 'cayman islands', text: 'cayman islands' },
  { id: 'chad', text: 'chad' },
  { id: 'chile', text: 'chile' },
  { id: 'china', text: 'china' },
  { id: 'colombia', text: 'colombia' },
  { id: 'congo', text: 'congo' },
  { id: 'cook islands', text: 'cook islands' },
  { id: 'costa rica', text: 'costa rica' },
  { id: 'cote d ivoire', text: 'cote d ivoire' },
  { id: 'croatia', text: 'croatia' },
  { id: 'cruise ship', text: 'cruise ship' },
  { id: 'cuba', text: 'cuba' },
  { id: 'cyprus', text: 'cyprus' },
  { id: 'czech republic', text: 'czech republic' },
  { id: 'denmark', text: 'denmark' },
  { id: 'djibouti', text: 'djibouti' },
  { id: 'dominica', text: 'dominica' },
  { id: 'dominican republic', text: 'dominican republic' },
  { id: 'ecuador', text: 'ecuador' },
  { id: 'egypt', text: 'egypt' },
  { id: 'el salvador', text: 'el salvador' },
  { id: 'equatorial guinea', text: 'equatorial guinea' },
  { id: 'estonia', text: 'estonia' },
  { id: 'ethiopia', text: 'ethiopia' },
  { id: 'falkland islands', text: 'falkland islands' },
  { id: 'faroe islands', text: 'faroe islands' },
  { id: 'fiji', text: 'fiji' },
  { id: 'finland', text: 'finland' },
  { id: 'france', text: 'france' },
  { id: 'french polynesia', text: 'french polynesia' },
  { id: 'french west indies', text: 'french west indies' },
  { id: 'gabon', text: 'gabon' },
  { id: 'gambia', text: 'gambia' },
  { id: 'georgia', text: 'georgia' },
  { id: 'germany', text: 'germany' },
  { id: 'ghana', text: 'ghana' },
  { id: 'gibraltar', text: 'gibraltar' },
  { id: 'greece', text: 'greece' },
  { id: 'greenland', text: 'greenland' },
  { id: 'grenada', text: 'grenada' },
  { id: 'guam', text: 'guam' },
  { id: 'guatemala', text: 'guatemala' },
  { id: 'guernsey', text: 'guernsey' },
  { id: 'guinea', text: 'guinea' },
  { id: 'guinea bissau', text: 'guinea bissau' },
  { id: 'guyana', text: 'guyana' },
  { id: 'haiti', text: 'haiti' },
  { id: 'honduras', text: 'honduras' },
  { id: 'hong kong', text: 'hong kong' },
  { id: 'hungary', text: 'hungary' },
  { id: 'iceland', text: 'iceland' },
  { id: 'india', text: 'india' },
  { id: 'indonesia', text: 'indonesia' },
  { id: 'iran', text: 'iran' },
  { id: 'iraq', text: 'iraq' },
  { id: 'ireland', text: 'ireland' },
  { id: 'isle of man', text: 'isle of man' },
  { id: 'israel', text: 'israel' },
  { id: 'italy', text: 'italy' },
  { id: 'jamaica', text: 'jamaica' },
  { id: 'japan', text: 'japan' },
  { id: 'jersey', text: 'jersey' },
  { id: 'jordan', text: 'jordan' },
  { id: 'kazakhstan', text: 'kazakhstan' },
  { id: 'kenya', text: 'kenya' },
  { id: 'kuwait', text: 'kuwait' },
  { id: 'kyrgyz republic', text: 'kyrgyz republic' },
  { id: 'laos', text: 'laos' },
  { id: 'latvia', text: 'latvia' },
  { id: 'lebanon', text: 'lebanon' },
  { id: 'lesotho', text: 'lesotho' },
  { id: 'liberia', text: 'liberia' },
  { id: 'libya', text: 'libya' },
  { id: 'liechtenstein', text: 'liechtenstein' },
  { id: 'lithuania', text: 'lithuania' },
  { id: 'luxembourg', text: 'luxembourg' },
  { id: 'macau', text: 'macau' },
  { id: 'macedonia', text: 'macedonia' },
  { id: 'madagascar', text: 'madagascar' },
  { id: 'malawi', text: 'malawi' },
  { id: 'malaysia', text: 'malaysia' },
  { id: 'maldives', text: 'maldives' },
  { id: 'mali', text: 'mali' },
  { id: 'malta', text: 'malta' },
  { id: 'mauritania', text: 'mauritania' },
  { id: 'mauritius', text: 'mauritius' },
  { id: 'mexico', text: 'mexico' },
  { id: 'moldova', text: 'moldova' },
  { id: 'monaco', text: 'monaco' },
  { id: 'mongolia', text: 'mongolia' },
  { id: 'montenegro', text: 'montenegro' },
  { id: 'montserrat', text: 'montserrat' },
  { id: 'morocco', text: 'morocco' },
  { id: 'mozambique', text: 'mozambique' },
  { id: 'namibia', text: 'namibia' },
  { id: 'nepal', text: 'nepal' },
  { id: 'netherlands', text: 'netherlands' },
  { id: 'new caledonia', text: 'new caledonia' },
  { id: 'new zealand', text: 'new zealand' },
  { id: 'nicaragua', text: 'nicaragua' },
  { id: 'niger', text: 'niger' },
  { id: 'nigeria', text: 'nigeria' },
  { id: 'norway', text: 'norway' },
  { id: 'oman', text: 'oman' },
  { id: 'pakistan', text: 'pakistan' },
  { id: 'palestine', text: 'palestine' },
  { id: 'panama', text: 'panama' },
  { id: 'paraguay', text: 'paraguay' },
  { id: 'peru', text: 'peru' },
  { id: 'philippines', text: 'philippines' },
  { id: 'poland', text: 'poland' },
  { id: 'portugal', text: 'portugal' },
  { id: 'puerto rico', text: 'puerto rico' },
  { id: 'qatar', text: 'qatar' },
  { id: 'romania', text: 'romania' },
  { id: 'russia', text: 'russia' },
  { id: 'senegal', text: 'senegal' },
  { id: 'seychelles', text: 'seychelles' },
  { id: 'singapore', text: 'singapore' },
  { id: 'south africa', text: 'south africa' },
  { id: 'south korea', text: 'south korea' },
  { id: 'spain', text: 'spain' },
  { id: 'sweden', text: 'sweden' },
  { id: 'switzerland', text: 'switzerland' },
  { id: 'syria', text: 'syria' },
  { id: 'taiwan', text: 'taiwan' },
  { id: 'tanzania', text: 'tanzania' },
  { id: 'thailand', text: 'thailand' },
  { id: 'trinidad &amp; tobago', text: 'trinidad &amp; tobago' },
  { id: 'tunisia', text: 'tunisia' },
  { id: 'turkey', text: 'turkey' },
  { id: 'uganda', text: 'uganda' },
  { id: 'ukraine', text: 'ukraine' },
  { id: 'united arab emirates', text: 'united arab emirates' },
  { id: 'united kingdom', text: 'united kingdom' },
  { id: 'united states of america', text: 'united states of america' },
  { id: 'uruguay', text: 'uruguay' },
  { id: 'uzbekistan', text: 'uzbekistan' },
  { id: 'venezuela', text: 'venezuela' },
  { id: 'vietnam', text: 'vietnam' },
  { id: 'virgin islands (us)', text: 'virgin islands (us)' },
  { id: 'zambia', text: 'zambia' },
  { id: 'zimbabwe', text: 'zimbabwe' },
];
